apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kd711tyjz-go
  janus-idp.io/tekton: kd711tyjz-go
  backstage.io/kubernetes-id: kd711tyjz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kd711tyjz-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
