apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kd711tyjz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kd711tyjz-go 
  name: kd711tyjz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kd711tyjz-go 
